import type { Metadata } from "next";
import { Container } from "./components/Container";

const Head = dynamic(() => import('./components/Head'), { ssr: false })

import "./globals.scss";
import dynamic from "next/dynamic";

export const metadata: Metadata = {
  title: "Cursos online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="pt-BR">
      <body>
        <Container>
          <Head />
          <main>{children}</main>
        </Container>
      </body>
    </html>
  );
}
