import type { Metadata } from "next";
import { Container } from "./components/Container";
import { Head } from "./components/Head";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        <Container>
          <Head />
          <main>{children}</main>
        </Container>
      </body>
    </html>
  );
}
