version: "3.7"

services:
  mongodb:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      INIT_WAIT_SEC: 3
    ports:
      - "27017:27017"

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html

  nginx:
    image: nginx
    container_name: nginx
    ports:
        - 80:80
        - 443:443
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    networks:
      - nginx-network

networks:
  nginx-network:  # Defina uma rede personalizada para comunicação entre os serviços
    driver: bridge

volumes:
  db-data: {}
  nextcloud: {}
